### ISSUE TITLE
入口问题

### ISSUE THREAD

**Issue by siasvip** [tearfulDalvik/passport-android#2]
自己设置的入口自己忘记了，现在不知道怎么办啦！

**Comment by tearfulDalvik** [comment]
备份数据库了吗。。没有的话就只能钛备份备份后恢复。有一种情况是passport被杀后台app杀了，你可以去设置里找到passport点击管理空间以后再去电话程序拨号试试

**Comment by tearfulDalvik** [comment]
鉴于长时间未回复，已关闭此 issue. 如果仍有问题再重新打开
